# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Workflows commands (::set-output): https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

name: CI - Test Build âš™ğŸ¤–

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  test_on_node:
    name: Test Build âš™ğŸ› 

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x, 12.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} ğŸ“¦
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path ğŸˆ
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules ğŸ§¶
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install Dependencies ğŸŠ
        run: yarn install --frozen-lockfile --check-files

      - name: Test Build ğŸ› 
        run: yarn build
